CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

GRANT USAGE, CREATE ON SCHEMA bronze TO CURRENT_USER;
GRANT USAGE, CREATE ON SCHEMA silver TO CURRENT_USER;
GRANT USAGE, CREATE ON SCHEMA gold TO CURRENT_USER;